name: theopencanvas
favicon: null
layout_spectrum: 0.25298
typography_spectrum: 0.36969
title: the open canvas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7e7e7e'
    - '#2e2e2e'
    - '#cdcdcd'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.8275231516454369
purpose: []
